# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alef < Formula
  desc 'Opinionated polyglot binding generator for Rust libraries'
  homepage 'https://github.com/kreuzberg-dev/alef'
  version '0.4.1'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-aarch64-apple-darwin.tar.gz'
      sha256 "cfc17deb663852755749a575a898d104c9b3ac4afb87e7eaa88bfd7cbcc8c7de"

      define_method(:install) do
        bin.install 'alef'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-x86_64-unknown-linux-gnu.tar.gz'
      sha256 "cfc17deb663852755749a575a898d104c9b3ac4afb87e7eaa88bfd7cbcc8c7de"
      define_method(:install) do
        bin.install 'alef'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-aarch64-unknown-linux-gnu.tar.gz'
      sha256 "cfc17deb663852755749a575a898d104c9b3ac4afb87e7eaa88bfd7cbcc8c7de"
      define_method(:install) do
        bin.install 'alef'
      end
    end
  end

  test do
    system "#{bin}/alef", '--help'
  end
end

bottle do
  root_url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.8.2'
  sha256 cellar: :any_skip_relocation, arm64_sequoia: 'd489769644152c7eca97311e1b5c3f709c7f82f35272c7fe5946996268ff9f3d'
end

  bottle do
    root_url "https://github.com/kreuzberg-dev/alef/releases/download/v0.11.10"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "a626f54eae5db2c2511b001ac2b2072f50789770b183d2962240725cc67dcb3c"
  end