# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alef < Formula
  desc 'Opinionated polyglot binding generator for Rust libraries'
  homepage 'https://github.com/kreuzberg-dev/alef'
  version '0.4.1'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-aarch64-apple-darwin.tar.gz'
      sha256 "105a27f856bf57516cb661081cedc7bd92c33eec5b54d7c7d285df0eb816767a"

      define_method(:install) do
        bin.install 'alef'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-x86_64-unknown-linux-gnu.tar.gz'
      sha256 "105a27f856bf57516cb661081cedc7bd92c33eec5b54d7c7d285df0eb816767a"
      define_method(:install) do
        bin.install 'alef'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/kreuzberg-dev/alef/releases/download/v0.4.1/alef-aarch64-unknown-linux-gnu.tar.gz'
      sha256 "105a27f856bf57516cb661081cedc7bd92c33eec5b54d7c7d285df0eb816767a"
      define_method(:install) do
        bin.install 'alef'
      end
    end
  end

  test do
    system "#{bin}/alef", '--help'
  end
end

  bottle do
    root_url "https://github.com/kreuzberg-dev/alef/releases/download/v0.7.6"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "9ed028a652b4ddb283f7addda69df557a0c40862e492f4de96818844b078d195"
  end